export { default as Home } from './Home'
export { default as TarotTable } from './TarotTable'
export { default as Reading } from './Reading'
export { default as Arcanums } from './Arcanums'
export { default as Configs } from './Configs/Configs'
